<#
.SYNOPSIS
    Purchases Azure Reserved Instances based on the gap analysis report.

.DESCRIPTION
    Reads the purchase summary CSV generated by Find-VMsWithoutReservations.ps1
    and purchases reserved instances for each VM size/location combination.

    Runs in dry-run mode by default. You must explicitly pass -Confirm to
    execute actual purchases.

.PARAMETER SummaryPath
    Path to the purchase summary CSV. Defaults to ~/ri-gap-report-summary.csv.

.PARAMETER Term
    Reservation term. Valid values: P1Y (1 year) or P3Y (3 years).
    Defaults to P1Y.

.PARAMETER Scope
    Reservation scope. Valid values: Shared, Single.
    Shared applies across all subscriptions in the billing account.
    Single restricts to a specific subscription.
    Defaults to Shared.

.PARAMETER AppliedSubscriptionId
    Required when Scope is "Single". The subscription ID to apply the
    reservation to.

.PARAMETER BillingSubscriptionId
    The subscription ID used for billing the reservation purchase.
    Required parameter.

.PARAMETER Confirm
    Actually execute the purchases. Without this flag, the script runs
    in dry-run mode and only shows what would be purchased.

.EXAMPLE
    # Dry run (no purchases made):
    .\Purchase-ReservedInstances.ps1 -BillingSubscriptionId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

    # Actual purchase, 1-year term, shared scope:
    .\Purchase-ReservedInstances.ps1 -BillingSubscriptionId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -Confirm

    # Actual purchase, 3-year term, single subscription scope:
    .\Purchase-ReservedInstances.ps1 -BillingSubscriptionId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -Term P3Y -Scope Single -AppliedSubscriptionId "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy" -Confirm
#>

param(
    [string]$SummaryPath = "$HOME/ri-gap-report-summary.csv",

    [ValidateSet("P1Y", "P3Y")]
    [string]$Term = "P1Y",

    [ValidateSet("Shared", "Single")]
    [string]$Scope = "Shared",

    [string]$AppliedSubscriptionId,

    [Parameter(Mandatory = $true)]
    [string]$BillingSubscriptionId,

    [switch]$Confirm
)

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------
# Validation
# ---------------------------------------------------------------
if ($Scope -eq "Single" -and -not $AppliedSubscriptionId) {
    Write-Error "AppliedSubscriptionId is required when Scope is 'Single'."
    return
}

if (-not (Test-Path $SummaryPath)) {
    Write-Error "Summary file not found at $SummaryPath. Run Find-VMsWithoutReservations.ps1 first."
    return
}

$summary = Import-Csv -Path $SummaryPath
if ($summary.Count -eq 0) {
    Write-Host "No reservations to purchase. The summary file is empty." -ForegroundColor Green
    return
}

# ---------------------------------------------------------------
# Display purchase plan
# ---------------------------------------------------------------
$termDisplay = if ($Term -eq "P1Y") { "1 Year" } else { "3 Year" }

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Reserved Instance Purchase Plan" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

Write-Host "Term:                  $termDisplay" -ForegroundColor White
Write-Host "Scope:                 $Scope" -ForegroundColor White
Write-Host "Billing Subscription:  $BillingSubscriptionId" -ForegroundColor White
if ($Scope -eq "Single") {
    Write-Host "Applied Subscription:  $AppliedSubscriptionId" -ForegroundColor White
}
Write-Host ""

Write-Host "Reservations to purchase:" -ForegroundColor Yellow
Write-Host "-------------------------" -ForegroundColor Yellow
$summary | Format-Table -AutoSize

if (-not $Confirm) {
    Write-Host "*** DRY RUN MODE ***" -ForegroundColor Red
    Write-Host "No purchases will be made. Pass -Confirm to execute.`n" -ForegroundColor Red
    Write-Host "Example:" -ForegroundColor Gray
    Write-Host "  .\Purchase-ReservedInstances.ps1 -BillingSubscriptionId `"$BillingSubscriptionId`" -Confirm`n" -ForegroundColor Gray
    return
}

# ---------------------------------------------------------------
# Final confirmation prompt
# ---------------------------------------------------------------
Write-Host "*** LIVE PURCHASE MODE ***" -ForegroundColor Red
Write-Host "This will purchase $($summary.Count) reservation order(s).`n" -ForegroundColor Red

$response = Read-Host "Type 'PURCHASE' to proceed (anything else cancels)"
if ($response -ne "PURCHASE") {
    Write-Host "`nPurchase cancelled.`n" -ForegroundColor Yellow
    return
}

# ---------------------------------------------------------------
# Execute purchases via REST API
# ---------------------------------------------------------------
Write-Host "`nStarting reservation purchases...`n" -ForegroundColor Yellow

$results = @()

foreach ($item in $summary) {
    $vmSize = $item.VMSize
    $location = $item.Location
    $quantity = [int]$item.Quantity

    $reservationOrderId = [guid]::NewGuid().ToString()
    $displayName = "RI-$vmSize-$location-$(Get-Date -Format 'yyyyMMdd')"

    Write-Host "Purchasing: $quantity x $vmSize in $location ($termDisplay)..." -ForegroundColor White

    # Build the request body for the reservation purchase
    $body = @{
        sku        = @{
            name = $vmSize
        }
        location   = $location
        properties = @{
            reservedResourceType = "VirtualMachines"
            billingScopeId       = "/subscriptions/$BillingSubscriptionId"
            term                 = $Term
            quantity             = $quantity
            displayName          = $displayName
            appliedScopeType     = $Scope
            renew                = $false
        }
    }

    if ($Scope -eq "Single") {
        $body.properties.appliedScopes = @("/subscriptions/$AppliedSubscriptionId")
    }

    $jsonBody = $body | ConvertTo-Json -Depth 10

    # PUT to the reservation order purchase API
    $apiPath = "/providers/Microsoft.Capacity/reservationOrders/$($reservationOrderId)?api-version=2022-11-01"

    try {
        $response = Invoke-AzRestMethod -Method PUT -Path $apiPath -Payload $jsonBody

        if ($response.StatusCode -in 200, 201, 202) {
            Write-Host "  Submitted successfully (Status: $($response.StatusCode))" -ForegroundColor Green

            $results += [PSCustomObject]@{
                VMSize             = $vmSize
                Location           = $location
                Quantity           = $quantity
                Term               = $termDisplay
                ReservationOrderId = $reservationOrderId
                Status             = "Submitted"
                StatusCode         = $response.StatusCode
            }
        }
        else {
            $errorContent = $response.Content | ConvertFrom-Json -ErrorAction SilentlyContinue
            $errorMessage = if ($errorContent.error.message) { $errorContent.error.message } else { $response.Content }
            Write-Host "  Failed (Status: $($response.StatusCode)): $errorMessage" -ForegroundColor Red

            $results += [PSCustomObject]@{
                VMSize             = $vmSize
                Location           = $location
                Quantity           = $quantity
                Term               = $termDisplay
                ReservationOrderId = $reservationOrderId
                Status             = "Failed"
                StatusCode         = $response.StatusCode
            }
        }
    }
    catch {
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red

        $results += [PSCustomObject]@{
            VMSize             = $vmSize
            Location           = $location
            Quantity           = $quantity
            Term               = $termDisplay
            ReservationOrderId = $reservationOrderId
            Status             = "Error"
            StatusCode         = "N/A"
        }
    }
}

# ---------------------------------------------------------------
# Purchase results
# ---------------------------------------------------------------
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Purchase Results" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

$results | Format-Table -AutoSize

$resultsPath = "$HOME/ri-purchase-results.csv"
$results | Export-Csv -Path $resultsPath -NoTypeInformation -Force
Write-Host "Results saved to: $resultsPath`n" -ForegroundColor Green

$submitted = ($results | Where-Object { $_.Status -eq "Submitted" }).Count
$failed = ($results | Where-Object { $_.Status -ne "Submitted" }).Count

Write-Host "Submitted: $submitted  |  Failed: $failed" -ForegroundColor $(if ($failed -gt 0) { "Yellow" } else { "Green" })
Write-Host ""

if ($submitted -gt 0) {
    Write-Host "Reservation purchases are asynchronous. It may take several minutes" -ForegroundColor Cyan
    Write-Host "for them to appear in the Azure portal under Cost Management + Billing" -ForegroundColor Cyan
    Write-Host "> Reservations. You can also check status with:" -ForegroundColor Cyan
    Write-Host "  Get-AzReservationOrder | Where-Object { `$_.CreatedDateTime -gt (Get-Date).AddHours(-1) }`n" -ForegroundColor Gray
}
